"""initial migration

Revision ID: 71cb9dafd972
Revises: 
Create Date: 2026-06-18 14:45:56.894558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cb9dafd972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('destination',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)

    # ### end Alembic commands ###
