"""cria tabela visitor_categories

Revision ID: d3cb0ac9d94d
Revises: 565ddf0e2f18
Create Date: 2026-06-22 15:04:13.540640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cb0ac9d94d'
down_revision = '565ddf0e2f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('btn_class', sa.String(length=60), nullable=True),
    sa.Column('badge_class', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_categories')
    # ### end Alembic commands ###
